<?xml version='1.0' encoding='utf-8'?>
<ReadingList xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Name>Dan Slott’s Spider-Man: Part 1</Name>
  <NumIssues>109</NumIssues>
  <Books>
    <Book Series="Amazing Spider-Man" Number="546" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="547" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="548" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="559" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="560" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="561" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="564" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="568" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="569" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="570" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="571" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="572" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="573" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="581" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="582" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="590" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="591" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="600" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="618" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="619" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="620" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="621" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="648" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="649" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="650" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="651" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="652" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="653" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="654" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="655" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="656" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="657" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="658" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="659" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="660" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="662" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="663" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="664" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="665" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="666" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="667" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="668" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="669" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="670" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="671" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="672" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="673" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="674" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="675" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="676" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="678" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="679" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="680" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="681" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="682" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="683" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="684" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="685" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="686" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="687" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="688" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="689" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="690" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="691" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="692" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="693" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="694" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="695" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="696" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="697" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="698" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="699" Year="1999" />
    <Book Series="Amazing Spider-Man" Number="700" Year="1999" />
    <Book Series="Superior Spider-Man" Number="1" Year="2013" />
    <Book Series="Superior Spider-Man" Number="2" Year="2013" />
    <Book Series="Superior Spider-Man" Number="3" Year="2013" />
    <Book Series="Superior Spider-Man" Number="4" Year="2013" />
    <Book Series="Superior Spider-Man" Number="5" Year="2013" />
    <Book Series="Superior Spider-Man" Number="6" Year="2013" />
    <Book Series="Superior Spider-Man" Number="6.5" Year="2013" />
    <Book Series="Superior Spider-Man" Number="7" Year="2013" />
    <Book Series="Superior Spider-Man" Number="8" Year="2013" />
    <Book Series="Superior Spider-Man" Number="9" Year="2013" />
    <Book Series="Superior Spider-Man" Number="10" Year="2013" />
    <Book Series="Superior Spider-Man" Number="11" Year="2013" />
    <Book Series="Superior Spider-Man" Number="12" Year="2013" />
    <Book Series="Superior Spider-Man" Number="13" Year="2013" />
    <Book Series="Superior Spider-Man" Number="14" Year="2013" />
    <Book Series="Superior Spider-Man" Number="15" Year="2013" />
    <Book Series="Superior Spider-Man" Number="16" Year="2013" />
    <Book Series="Superior Spider-Man" Number="17" Year="2013" />
    <Book Series="Superior Spider-Man" Number="18" Year="2013" />
    <Book Series="Superior Spider-Man" Number="19" Year="2013" />
    <Book Series="Superior Spider-Man" Number="20" Year="2013" />
    <Book Series="Superior Spider-Man" Number="21" Year="2013" />
    <Book Series="Superior Spider-Man Annual" Number="1" Year="2013" />
    <Book Series="Superior Spider-Man" Number="22" Year="2013" />
    <Book Series="Superior Spider-Man" Number="23" Year="2013" />
    <Book Series="Superior Spider-Man" Number="24" Year="2013" />
    <Book Series="Superior Spider-Man" Number="25" Year="2013" />
    <Book Series="Superior Spider-Man" Number="26" Year="2013" />
    <Book Series="Superior Spider-Man" Number="27" Year="2013" />
    <Book Series="Superior Spider-Man" Number="28" Year="2013" />
    <Book Series="Superior Spider-Man" Number="29" Year="2013" />
    <Book Series="Superior Spider-Man Annual" Number="2" Year="2013" />
    <Book Series="Superior Spider-Man" Number="30" Year="2013" />
    <Book Series="Superior Spider-Man" Number="31" Year="2013" />
    <Book Series="Superior Spider-Man" Number="32" Year="2013" />
    <Book Series="Superior Spider-Man" Number="33" Year="2013" />
  </Books>
</ReadingList>