<?xml version='1.0' encoding='utf-8'?>
<ReadingList xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Name>Titans: Hard Feelings</Name>
  <NumIssues>143</NumIssues>
  <Books>
    <Book Series="The New Titans" Number="1" Year="1984" />
    <Book Series="The New Titans" Number="2" Year="1984" />
    <Book Series="The New Titans" Number="3" Year="1984" />
    <Book Series="The New Titans" Number="4" Year="1985" />
    <Book Series="The New Titans" Number="5" Year="1985" />
    <Book Series="The New Titans" Number="6" Year="1985" />
    <Book Series="The New Titans" Number="7" Year="1985" />
    <Book Series="The New Titans" Number="8" Year="1985" />
    <Book Series="The New Titans" Number="9" Year="1985" />
    <Book Series="The New Titans" Number="1" Year="1985" />
    <Book Series="The New Titans" Number="10" Year="1985" />
    <Book Series="The New Titans" Number="11" Year="1985" />
    <Book Series="The New Titans" Number="12" Year="1985" />
    <Book Series="The New Titans" Number="13" Year="1985" />
    <Book Series="The New Titans" Number="14" Year="1985" />
    <Book Series="The New Titans" Number="15" Year="1985" />
    <Book Series="The New Titans" Number="16" Year="1986" />
    <Book Series="The New Titans" Number="17" Year="1986" />
    <Book Series="The New Titans" Number="18" Year="1986" />
    <Book Series="The New Titans" Number="19" Year="1986" />
    <Book Series="The New Titans" Number="20" Year="1986" />
    <Book Series="The New Titans" Number="21" Year="1986" />
    <Book Series="The New Titans" Number="22" Year="1986" />
    <Book Series="The New Titans" Number="23" Year="1986" />
    <Book Series="The New Titans" Number="2" Year="1986" />
    <Book Series="The New Titans" Number="24" Year="1986" />
    <Book Series="The New Titans" Number="25" Year="1986" />
    <Book Series="The New Titans" Number="26" Year="1986" />
    <Book Series="The New Titans" Number="27" Year="1987" />
    <Book Series="The New Titans" Number="28" Year="1987" />
    <Book Series="The New Titans" Number="29" Year="1987" />
    <Book Series="The New Titans" Number="30" Year="1987" />
    <Book Series="The New Titans" Number="31" Year="1987" />
    <Book Series="The New Titans" Number="32" Year="1987" />
    <Book Series="The New Titans" Number="33" Year="1987" />
    <Book Series="The New Titans" Number="34" Year="1987" />
    <Book Series="The New Titans" Number="3" Year="1987" />
    <Book Series="The New Titans" Number="35" Year="1987" />
    <Book Series="The New Titans" Number="36" Year="1987" />
    <Book Series="The New Titans" Number="37" Year="1987" />
    <Book Series="The New Titans" Number="38" Year="1987" />
    <Book Series="The New Titans" Number="39" Year="1988" />
    <Book Series="The New Titans" Number="40" Year="1988" />
    <Book Series="The New Titans" Number="41" Year="1988" />
    <Book Series="The New Titans" Number="42" Year="1988" />
    <Book Series="The New Titans" Number="43" Year="1988" />
    <Book Series="The New Titans" Number="44" Year="1988" />
    <Book Series="The New Titans" Number="45" Year="1988" />
    <Book Series="The New Titans" Number="46" Year="1988" />
    <Book Series="The New Titans" Number="4" Year="1988" />
    <Book Series="The New Titans" Number="50" Year="1988" />
    <Book Series="The New Titans" Number="47" Year="1988" />
    <Book Series="The New Titans" Number="51" Year="1988" />
    <Book Series="The New Titans" Number="48" Year="1988" />
    <Book Series="The New Titans" Number="49" Year="1988" />
    <Book Series="The New Titans" Number="52" Year="1988" />
    <Book Series="The New Titans" Number="53" Year="1989" />
    <Book Series="The New Titans" Number="54" Year="1989" />
    <Book Series="The New Titans" Number="55" Year="1989" />
    <Book Series="The New Titans" Number="56" Year="1989" />
    <Book Series="The New Titans" Number="57" Year="1989" />
    <Book Series="The New Titans" Number="58" Year="1989" />
    <Book Series="The New Titans" Number="5" Year="1989" />
    <Book Series="The New Titans" Number="59" Year="1989" />
    <Book Series="The New Titans" Number="60" Year="1989" />
    <Book Series="The New Titans" Number="61" Year="1989" />
    <Book Series="The New Titans" Number="62" Year="1989" />
    <Book Series="The New Titans" Number="63" Year="1989" />
    <Book Series="The New Titans" Number="64" Year="1990" />
    <Book Series="The New Titans" Number="65" Year="1990" />
    <Book Series="The New Titans" Number="66" Year="1990" />
    <Book Series="The New Titans" Number="67" Year="1990" />
    <Book Series="The New Titans" Number="68" Year="1990" />
    <Book Series="The New Titans" Number="69" Year="1990" />
    <Book Series="The New Titans" Number="6" Year="1990" />
    <Book Series="The New Titans" Number="70" Year="1990" />
    <Book Series="The New Titans" Number="71" Year="1990" />
    <Book Series="The New Titans" Number="72" Year="1990" />
    <Book Series="The New Titans" Number="73" Year="1990" />
    <Book Series="The New Titans" Number="74" Year="1991" />
    <Book Series="The New Titans" Number="75" Year="1991" />
    <Book Series="The New Titans" Number="76" Year="1991" />
    <Book Series="The New Titans" Number="77" Year="1991" />
    <Book Series="The New Titans" Number="78" Year="1991" />
    <Book Series="The New Titans" Number="79" Year="1991" />
    <Book Series="The New Titans" Number="7" Year="1991" />
    <Book Series="The New Titans" Number="80" Year="1991" />
    <Book Series="The New Titans" Number="81" Year="1991" />
    <Book Series="The New Titans" Number="82" Year="1991" />
    <Book Series="The New Titans" Number="83" Year="1991" />
    <Book Series="The New Titans" Number="84" Year="1992" />
    <Book Series="The New Titans" Number="85" Year="1992" />
    <Book Series="The New Titans" Number="86" Year="1992" />
    <Book Series="The New Titans" Number="87" Year="1992" />
    <Book Series="The New Titans" Number="88" Year="1992" />
    <Book Series="The New Titans" Number="89" Year="1992" />
    <Book Series="The New Titans" Number="90" Year="1992" />
    <Book Series="The New Titans" Number="8" Year="1992" />
    <Book Series="The New Titans" Number="91" Year="1992" />
    <Book Series="The New Titans" Number="92" Year="1992" />
    <Book Series="The New Titans" Number="93" Year="1992" />
    <Book Series="The New Titans" Number="94" Year="1993" />
    <Book Series="The New Titans" Number="95" Year="1993" />
    <Book Series="The New Titans" Number="96" Year="1993" />
    <Book Series="The New Titans" Number="97" Year="1993" />
    <Book Series="The New Titans" Number="98" Year="1993" />
    <Book Series="The New Titans" Number="99" Year="1993" />
    <Book Series="The New Titans" Number="9" Year="1993" />
    <Book Series="The New Titans" Number="100" Year="1993" />
    <Book Series="The New Titans" Number="101" Year="1993" />
    <Book Series="The New Titans" Number="102" Year="1993" />
    <Book Series="The New Titans" Number="103" Year="1993" />
    <Book Series="The New Titans" Number="104" Year="1993" />
    <Book Series="The New Titans" Number="105" Year="1993" />
    <Book Series="The New Titans" Number="106" Year="1993" />
    <Book Series="The New Titans" Number="107" Year="1993" />
    <Book Series="The New Titans" Number="108" Year="1993" />
    <Book Series="The New Titans" Number="109" Year="1994" />
    <Book Series="The New Titans" Number="110" Year="1994" />
    <Book Series="The New Titans" Number="111" Year="1994" />
    <Book Series="The New Titans" Number="10" Year="1994" />
    <Book Series="The New Titans" Number="112" Year="1994" />
    <Book Series="The New Titans" Number="113" Year="1994" />
    <Book Series="The New Titans" Number="114" Year="1994" />
    <Book Series="The New Titans" Number="0" Year="1994" />
    <Book Series="The New Titans" Number="115" Year="1994" />
    <Book Series="The New Titans" Number="116" Year="1994" />
    <Book Series="The New Titans" Number="117" Year="1994" />
    <Book Series="The New Titans" Number="118" Year="1994" />
    <Book Series="The New Titans" Number="119" Year="1995" />
    <Book Series="The New Titans" Number="120" Year="1995" />
    <Book Series="The New Titans" Number="121" Year="1995" />
    <Book Series="The New Titans" Number="11" Year="1995" />
    <Book Series="The New Titans" Number="122" Year="1995" />
    <Book Series="The New Titans" Number="123" Year="1995" />
    <Book Series="The New Titans" Number="124" Year="1995" />
    <Book Series="The New Titans" Number="125" Year="1995" />
    <Book Series="The New Titans" Number="126" Year="1995" />
    <Book Series="The New Titans" Number="127" Year="1995" />
    <Book Series="The New Titans" Number="128" Year="1995" />
    <Book Series="The New Titans" Number="129" Year="1995" />
    <Book Series="The New Titans" Number="130" Year="1995" />
    <Book Series="The New Titans" Number="1" Year="2018" />
  </Books>
</ReadingList>