<?xml version='1.0' encoding='utf-8'?>
<ReadingList xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Name>Superman: The Oz Effect</Name>
  <NumIssues>125</NumIssues>
  <Books>
    <Book Series="Superman: The Man of Steel" Number="1" Year="1991" />
    <Book Series="Superman: The Man of Steel" Number="2" Year="1991" />
    <Book Series="Superman: The Man of Steel" Number="3" Year="1991" />
    <Book Series="Superman: The Man of Steel" Number="4" Year="1991" />
    <Book Series="Superman: The Man of Steel" Number="5" Year="1991" />
    <Book Series="Superman: The Man of Steel" Number="6" Year="1991" />
    <Book Series="Superman: The Man of Steel" Number="7" Year="1991" />
    <Book Series="Superman: The Man of Steel" Number="8" Year="1991" />
    <Book Series="Superman: The Man of Steel" Number="9" Year="1992" />
    <Book Series="Superman: The Man of Steel" Number="10" Year="1992" />
    <Book Series="Superman: The Man of Steel" Number="11" Year="1992" />
    <Book Series="Superman: The Man of Steel" Number="12" Year="1992" />
    <Book Series="Superman: The Man of Steel" Number="13" Year="1992" />
    <Book Series="Superman: The Man of Steel" Number="1" Year="1992" />
    <Book Series="Superman: The Man of Steel" Number="14" Year="1992" />
    <Book Series="Superman: The Man of Steel" Number="15" Year="1992" />
    <Book Series="Superman: The Man of Steel" Number="16" Year="1992" />
    <Book Series="Superman: The Man of Steel" Number="17" Year="1992" />
    <Book Series="Superman: The Man of Steel" Number="18" Year="1992" />
    <Book Series="Superman: The Man of Steel" Number="19" Year="1992" />
    <Book Series="Superman: The Man of Steel" Number="20" Year="1992" />
    <Book Series="Superman: The Man of Steel" Number="21" Year="1993" />
    <Book Series="Superman: The Man of Steel" Number="22" Year="1993" />
    <Book Series="Superman: The Man of Steel" Number="2" Year="1993" />
    <Book Series="Superman: The Man of Steel" Number="23" Year="1993" />
    <Book Series="Superman: The Man of Steel" Number="24" Year="1993" />
    <Book Series="Superman: The Man of Steel" Number="25" Year="1993" />
    <Book Series="Superman: The Man of Steel" Number="26" Year="1993" />
    <Book Series="Superman: The Man of Steel" Number="27" Year="1993" />
    <Book Series="Superman: The Man of Steel" Number="28" Year="1993" />
    <Book Series="Superman: The Man of Steel" Number="29" Year="1993" />
    <Book Series="Superman: The Man of Steel" Number="30" Year="1993" />
    <Book Series="Superman: The Man of Steel" Number="31" Year="1994" />
    <Book Series="Superman: The Man of Steel" Number="32" Year="1994" />
    <Book Series="Superman: The Man of Steel" Number="33" Year="1994" />
    <Book Series="Superman: The Man of Steel" Number="34" Year="1994" />
    <Book Series="Superman: The Man of Steel" Number="35" Year="1994" />
    <Book Series="Superman: The Man of Steel" Number="36" Year="1994" />
    <Book Series="Superman: The Man of Steel" Number="37" Year="1994" />
    <Book Series="Superman: The Man of Steel" Number="1" Year="1994" />
    <Book Series="Superman: The Man of Steel" Number="38" Year="1994" />
    <Book Series="Superman: The Man of Steel" Number="39" Year="1994" />
    <Book Series="Superman: The Man of Steel" Number="40" Year="1994" />
    <Book Series="Superman: The Man of Steel" Number="41" Year="1994" />
    <Book Series="Superman: The Man of Steel" Number="42" Year="1995" />
    <Book Series="Superman: The Man of Steel" Number="43" Year="1995" />
    <Book Series="Superman: The Man of Steel" Number="44" Year="1995" />
    <Book Series="Superman: The Man of Steel" Number="45" Year="1995" />
    <Book Series="Superman: The Man of Steel" Number="46" Year="1995" />
    <Book Series="Superman: The Man of Steel" Number="47" Year="1995" />
    <Book Series="Superman: The Man of Steel" Number="48" Year="1995" />
    <Book Series="Superman: The Man of Steel" Number="49" Year="1995" />
    <Book Series="Superman: The Man of Steel" Number="50" Year="1995" />
    <Book Series="Superman: The Man of Steel" Number="51" Year="1995" />
    <Book Series="Superman: The Man of Steel" Number="52" Year="1995" />
    <Book Series="Superman: The Man of Steel" Number="53" Year="1995" />
    <Book Series="Superman: The Man of Steel" Number="54" Year="1996" />
    <Book Series="Superman: The Man of Steel" Number="55" Year="1996" />
    <Book Series="Superman: The Man of Steel" Number="56" Year="1996" />
    <Book Series="Superman: The Man of Steel" Number="57" Year="1996" />
    <Book Series="Superman: The Man of Steel" Number="58" Year="1996" />
    <Book Series="Superman: The Man of Steel" Number="59" Year="1996" />
    <Book Series="Superman: The Man of Steel" Number="60" Year="1996" />
    <Book Series="Superman: The Man of Steel" Number="61" Year="1996" />
    <Book Series="Superman: The Man of Steel" Number="62" Year="1996" />
    <Book Series="Superman: The Man of Steel" Number="63" Year="1996" />
    <Book Series="Superman: The Man of Steel" Number="64" Year="1996" />
    <Book Series="Superman: The Man of Steel" Number="65" Year="1997" />
    <Book Series="Superman: The Man of Steel" Number="66" Year="1997" />
    <Book Series="Superman: The Man of Steel" Number="67" Year="1997" />
    <Book Series="Superman: The Man of Steel" Number="68" Year="1997" />
    <Book Series="Superman: The Man of Steel" Number="69" Year="1997" />
    <Book Series="Superman: The Man of Steel" Number="70" Year="1997" />
    <Book Series="Superman: The Man of Steel" Number="71" Year="1997" />
    <Book Series="Superman: The Man of Steel" Number="72" Year="1997" />
    <Book Series="Superman: The Man of Steel" Number="73" Year="1997" />
    <Book Series="Superman: The Man of Steel" Number="74" Year="1997" />
    <Book Series="Superman: The Man of Steel" Number="75" Year="1997" />
    <Book Series="Superman: The Man of Steel" Number="76" Year="1997" />
    <Book Series="Superman: The Man of Steel" Number="77" Year="1998" />
    <Book Series="Superman: The Man of Steel" Number="78" Year="1998" />
    <Book Series="Superman: The Man of Steel" Number="79" Year="1998" />
    <Book Series="Superman: The Man of Steel" Number="80" Year="1998" />
    <Book Series="Superman: The Man of Steel" Number="81" Year="1998" />
    <Book Series="Superman: The Man of Steel" Number="82" Year="1998" />
    <Book Series="Superman: The Man of Steel" Number="83" Year="1998" />
    <Book Series="Superman: The Man of Steel" Number="84" Year="1998" />
    <Book Series="Superman: The Man of Steel" Number="85" Year="1998" />
    <Book Series="Superman: The Man of Steel" Number="86" Year="1998" />
    <Book Series="Superman: The Man of Steel" Number="87" Year="1999" />
    <Book Series="Superman: The Man of Steel" Number="88" Year="1999" />
    <Book Series="Superman: The Man of Steel" Number="89" Year="1999" />
    <Book Series="Superman: The Man of Steel" Number="90" Year="1999" />
    <Book Series="Superman: The Man of Steel" Number="91" Year="1999" />
    <Book Series="Superman: The Man of Steel" Number="92" Year="1999" />
    <Book Series="Superman: The Man of Steel" Number="93" Year="1999" />
    <Book Series="Superman: The Man of Steel" Number="94" Year="1999" />
    <Book Series="Superman: The Man of Steel" Number="95" Year="1999" />
    <Book Series="Superman: The Man of Steel" Number="96" Year="1999" />
    <Book Series="Superman: The Man of Steel" Number="97" Year="1999" />
    <Book Series="Superman: The Man of Steel" Number="98" Year="2000" />
    <Book Series="Superman: The Man of Steel" Number="99" Year="2000" />
    <Book Series="Superman: The Man of Steel" Number="100" Year="2000" />
    <Book Series="Superman: The Man of Steel" Number="101" Year="2000" />
    <Book Series="Superman: The Man of Steel" Number="102" Year="2000" />
    <Book Series="Superman: The Man of Steel" Number="103" Year="2000" />
    <Book Series="Superman: The Man of Steel" Number="104" Year="2000" />
    <Book Series="Superman: The Man of Steel" Number="105" Year="2000" />
    <Book Series="Superman: The Man of Steel" Number="106" Year="2000" />
    <Book Series="Superman: The Man of Steel" Number="107" Year="2000" />
    <Book Series="Superman: The Man of Steel" Number="108" Year="2000" />
    <Book Series="Superman: The Man of Steel" Number="109" Year="2000" />
    <Book Series="Superman: The Man of Steel" Number="110" Year="2001" />
    <Book Series="Superman: The Man of Steel" Number="111" Year="2001" />
    <Book Series="Superman: The Man of Steel" Number="112" Year="2001" />
    <Book Series="Superman: The Man of Steel" Number="113" Year="2001" />
    <Book Series="Superman: The Man of Steel" Number="114" Year="2001" />
    <Book Series="Superman: The Man of Steel" Number="115" Year="2001" />
    <Book Series="Superman: The Man of Steel" Number="116" Year="2001" />
    <Book Series="Superman: The Man of Steel" Number="117" Year="2001" />
    <Book Series="Superman: The Man of Steel" Number="118" Year="2001" />
    <Book Series="Superman: The Man of Steel" Number="119" Year="2001" />
    <Book Series="Superman: The Man of Steel" Number="120" Year="2001" />
    <Book Series="Superman: The Man of Steel" Number="130" Year="2002" />
    <Book Series="Superman: The Man of Steel" Number="131" Year="2002" />
  </Books>
</ReadingList>