<?xml version='1.0' encoding='utf-8'?>
<ReadingList xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Name>The Sandman: Preludes &amp; Nocturnes</Name>
  <NumIssues>99</NumIssues>
  <Books>
    <Book Series="The Sandman" Number="1" Year="1988" />
    <Book Series="The Sandman" Number="2" Year="1989" />
    <Book Series="The Sandman" Number="3" Year="1989" />
    <Book Series="The Sandman" Number="4" Year="1989" />
    <Book Series="The Sandman" Number="5" Year="1989" />
    <Book Series="The Sandman" Number="6" Year="1989" />
    <Book Series="The Sandman" Number="7" Year="1989" />
    <Book Series="The Sandman" Number="8" Year="1989" />
    <Book Series="The Sandman" Number="9" Year="1989" />
    <Book Series="The Sandman" Number="10" Year="1989" />
    <Book Series="The Sandman" Number="11" Year="1989" />
    <Book Series="The Sandman" Number="12" Year="1989" />
    <Book Series="The Sandman" Number="13" Year="1990" />
    <Book Series="The Sandman" Number="14" Year="1990" />
    <Book Series="The Sandman" Number="15" Year="1990" />
    <Book Series="The Sandman" Number="16" Year="1990" />
    <Book Series="The Sandman" Number="17" Year="1990" />
    <Book Series="The Sandman" Number="18" Year="1990" />
    <Book Series="The Sandman" Number="19" Year="1990" />
    <Book Series="The Sandman" Number="20" Year="1990" />
    <Book Series="The Sandman" Number="21" Year="1990" />
    <Book Series="The Sandman" Number="22" Year="1990" />
    <Book Series="The Sandman" Number="23" Year="1991" />
    <Book Series="The Sandman" Number="24" Year="1991" />
    <Book Series="The Sandman" Number="25" Year="1991" />
    <Book Series="The Sandman" Number="26" Year="1991" />
    <Book Series="The Sandman" Number="27" Year="1991" />
    <Book Series="The Sandman" Number="28" Year="1991" />
    <Book Series="The Sandman" Number="29" Year="1991" />
    <Book Series="The Sandman" Number="30" Year="1991" />
    <Book Series="The Sandman" Number="31" Year="1991" />
    <Book Series="The Sandman" Number="32" Year="1991" />
    <Book Series="The Sandman" Number="1" Year="1991" />
    <Book Series="The Sandman" Number="33" Year="1991" />
    <Book Series="The Sandman" Number="34" Year="1991" />
    <Book Series="The Sandman" Number="35" Year="1991" />
    <Book Series="The Sandman" Number="36" Year="1992" />
    <Book Series="The Sandman" Number="37" Year="1992" />
    <Book Series="The Sandman" Number="38" Year="1992" />
    <Book Series="The Sandman" Number="39" Year="1992" />
    <Book Series="The Sandman" Number="40" Year="1992" />
    <Book Series="The Sandman" Number="41" Year="1992" />
    <Book Series="The Sandman" Number="42" Year="1992" />
    <Book Series="The Sandman" Number="43" Year="1992" />
    <Book Series="The Sandman" Number="44" Year="1992" />
    <Book Series="The Sandman" Number="45" Year="1992" />
    <Book Series="The Sandman" Number="46" Year="1992" />
    <Book Series="The Sandman" Number="47" Year="1993" />
    <Book Series="The Sandman" Number="48" Year="1993" />
    <Book Series="The Sandman" Number="49" Year="1993" />
    <Book Series="The Sandman" Number="50" Year="1993" />
    <Book Series="The Sandman" Number="51" Year="1993" />
    <Book Series="The Sandman" Number="52" Year="1993" />
    <Book Series="The Sandman" Number="53" Year="1993" />
    <Book Series="The Sandman" Number="54" Year="1993" />
    <Book Series="The Sandman" Number="55" Year="1993" />
    <Book Series="The Sandman" Number="56" Year="1993" />
    <Book Series="The Sandman" Number="57" Year="1993" />
    <Book Series="The Sandman" Number="58" Year="1994" />
    <Book Series="The Sandman" Number="59" Year="1994" />
    <Book Series="The Sandman" Number="60" Year="1994" />
    <Book Series="The Sandman" Number="61" Year="1994" />
    <Book Series="The Sandman" Number="62" Year="1994" />
    <Book Series="The Sandman" Number="63" Year="1994" />
    <Book Series="The Sandman" Number="64" Year="1994" />
    <Book Series="The Sandman" Number="65" Year="1994" />
    <Book Series="The Sandman" Number="66" Year="1994" />
    <Book Series="The Sandman" Number="67" Year="1995" />
    <Book Series="The Sandman" Number="68" Year="1995" />
    <Book Series="The Sandman" Number="69" Year="1995" />
    <Book Series="The Sandman" Number="70" Year="1995" />
    <Book Series="The Sandman" Number="71" Year="1995" />
    <Book Series="The Sandman" Number="72" Year="1995" />
    <Book Series="The Sandman" Number="73" Year="1995" />
    <Book Series="The Sandman" Number="74" Year="1996" />
    <Book Series="The Sandman" Number="75" Year="1996" />
    <Book Series="The Sandman" Number="1" Year="2018" />
    <Book Series="The Sandman" Number="1" Year="2018" />
    <Book Series="The Sandman" Number="2" Year="2018" />
    <Book Series="The Sandman" Number="3" Year="2018" />
    <Book Series="The Sandman" Number="4" Year="2019" />
    <Book Series="The Sandman" Number="5" Year="2019" />
    <Book Series="The Sandman" Number="6" Year="2019" />
    <Book Series="The Sandman" Number="7" Year="2019" />
    <Book Series="The Sandman" Number="8" Year="2019" />
    <Book Series="The Sandman" Number="9" Year="2019" />
    <Book Series="The Sandman" Number="10" Year="2019" />
    <Book Series="The Sandman" Number="11" Year="2019" />
    <Book Series="The Sandman" Number="1" Year="2019" />
    <Book Series="The Sandman" Number="1" Year="2019" />
    <Book Series="The Sandman" Number="1" Year="2019" />
    <Book Series="The Sandman" Number="1" Year="2022" />
    <Book Series="The Sandman" Number="2" Year="2022" />
    <Book Series="The Sandman" Number="3" Year="2022" />
    <Book Series="The Sandman" Number="4" Year="2022" />
    <Book Series="The Sandman" Number="5" Year="2023" />
    <Book Series="The Sandman" Number="6" Year="2023" />
    <Book Series="The Sandman" Number="1" Year="2024" />
    <Book Series="The Sandman" Number="1" Year="2024" />
  </Books>
</ReadingList>