<?xml version='1.0' encoding='utf-8'?>
<ReadingList xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Name>Superman: The Black Ring</Name>
  <NumIssues>100</NumIssues>
  <Books>
    <Book Series="Superman/Batman" Number="1" Year="2003" />
    <Book Series="Superman/Batman" Number="2" Year="2003" />
    <Book Series="Superman/Batman" Number="10" Year="2004" />
    <Book Series="Superman/Batman" Number="11" Year="2004" />
    <Book Series="Superman/Batman" Number="12" Year="2004" />
    <Book Series="Superman/Batman" Number="13" Year="2004" />
    <Book Series="Superman/Batman" Number="14" Year="2004" />
    <Book Series="Superman/Batman" Number="15" Year="2004" />
    <Book Series="Superman/Batman" Number="16" Year="2004" />
    <Book Series="Superman/Batman" Number="17" Year="2005" />
    <Book Series="Superman/Batman" Number="18" Year="2005" />
    <Book Series="Superman/Batman" Number="19" Year="2005" />
    <Book Series="Superman/Batman" Number="20" Year="2005" />
    <Book Series="Superman/Batman" Number="21" Year="2005" />
    <Book Series="Superman/Batman" Number="22" Year="2005" />
    <Book Series="Superman/Batman" Number="23" Year="2005" />
    <Book Series="Superman/Batman" Number="24" Year="2006" />
    <Book Series="Superman/Batman" Number="25" Year="2006" />
    <Book Series="Superman/Batman" Number="26" Year="2006" />
    <Book Series="Superman/Batman" Number="1" Year="2006" />
    <Book Series="Superman/Batman" Number="31" Year="2006" />
    <Book Series="Superman/Batman" Number="32" Year="2007" />
    <Book Series="Superman/Batman" Number="33" Year="2007" />
    <Book Series="Superman/Batman" Number="34" Year="2007" />
    <Book Series="Superman/Batman" Number="35" Year="2007" />
    <Book Series="Superman/Batman" Number="36" Year="2007" />
    <Book Series="Superman/Batman" Number="37" Year="2007" />
    <Book Series="Superman/Batman" Number="38" Year="2007" />
    <Book Series="Superman/Batman" Number="39" Year="2007" />
    <Book Series="Superman/Batman" Number="40" Year="2007" />
    <Book Series="Superman/Batman" Number="41" Year="2007" />
    <Book Series="Superman/Batman" Number="42" Year="2007" />
    <Book Series="Superman/Batman" Number="43" Year="2007" />
    <Book Series="Superman/Batman" Number="44" Year="2007" />
    <Book Series="Superman/Batman" Number="45" Year="2008" />
    <Book Series="Superman/Batman" Number="46" Year="2008" />
    <Book Series="Superman/Batman" Number="2" Year="2008" />
    <Book Series="Superman/Batman" Number="47" Year="2008" />
    <Book Series="Superman/Batman" Number="48" Year="2008" />
    <Book Series="Superman/Batman" Number="49" Year="2008" />
    <Book Series="Superman/Batman" Number="50" Year="2008" />
    <Book Series="Superman/Batman" Number="51" Year="2008" />
    <Book Series="Superman/Batman" Number="52" Year="2008" />
    <Book Series="Superman/Batman" Number="53" Year="2008" />
    <Book Series="Superman/Batman" Number="54" Year="2008" />
    <Book Series="Superman/Batman" Number="3" Year="2009" />
    <Book Series="Superman/Batman" Number="55" Year="2009" />
    <Book Series="Superman/Batman" Number="56" Year="2009" />
    <Book Series="Superman/Batman" Number="57" Year="2009" />
    <Book Series="Superman/Batman" Number="58" Year="2009" />
    <Book Series="Superman/Batman" Number="59" Year="2009" />
    <Book Series="Superman/Batman" Number="60" Year="2009" />
    <Book Series="Superman/Batman" Number="61" Year="2009" />
    <Book Series="Superman/Batman" Number="62" Year="2009" />
    <Book Series="Superman/Batman" Number="63" Year="2009" />
    <Book Series="Superman/Batman" Number="64" Year="2009" />
    <Book Series="Superman/Batman" Number="65" Year="2009" />
    <Book Series="Superman/Batman" Number="66" Year="2009" />
    <Book Series="Superman/Batman" Number="67" Year="2009" />
    <Book Series="Superman/Batman" Number="68" Year="2010" />
    <Book Series="Superman/Batman" Number="69" Year="2010" />
    <Book Series="Superman/Batman" Number="70" Year="2010" />
    <Book Series="Superman/Batman" Number="71" Year="2010" />
    <Book Series="Superman/Batman" Number="72" Year="2010" />
    <Book Series="Superman/Batman" Number="4" Year="2010" />
    <Book Series="Superman/Batman" Number="3" Year="2010" />
    <Book Series="Superman/Batman" Number="4" Year="2010" />
    <Book Series="Superman/Batman" Number="5" Year="2010" />
    <Book Series="Superman/Batman" Number="6" Year="2010" />
    <Book Series="Superman/Batman" Number="7" Year="2010" />
    <Book Series="Superman/Batman" Number="8" Year="2010" />
    <Book Series="Superman/Batman" Number="9" Year="2010" />
    <Book Series="Superman/Batman" Number="73" Year="2010" />
    <Book Series="Superman/Batman" Number="74" Year="2010" />
    <Book Series="Superman/Batman" Number="75" Year="2010" />
    <Book Series="Superman/Batman" Number="27" Year="2010" />
    <Book Series="Superman/Batman" Number="28" Year="2010" />
    <Book Series="Superman/Batman" Number="29" Year="2010" />
    <Book Series="Superman/Batman" Number="76" Year="2010" />
    <Book Series="Superman/Batman" Number="30" Year="2010" />
    <Book Series="Superman/Batman" Number="77" Year="2010" />
    <Book Series="Superman/Batman" Number="78" Year="2010" />
    <Book Series="Superman/Batman" Number="79" Year="2010" />
    <Book Series="Superman/Batman" Number="80" Year="2011" />
    <Book Series="Superman/Batman" Number="81" Year="2011" />
    <Book Series="Superman/Batman" Number="82" Year="2011" />
    <Book Series="Superman/Batman" Number="5" Year="2011" />
    <Book Series="Superman/Batman" Number="83" Year="2011" />
    <Book Series="Superman/Batman" Number="84" Year="2011" />
    <Book Series="Superman/Batman" Number="85" Year="2011" />
    <Book Series="Superman/Batman" Number="86" Year="2011" />
    <Book Series="Superman/Batman" Number="87" Year="2011" />
    <Book Series="Superman/Batman" Number="1" Year="2012" />
    <Book Series="Superman/Batman" Number="1" Year="2014" />
    <Book Series="Superman/Batman" Number="2" Year="2014" />
    <Book Series="Superman/Batman" Number="1" Year="2016" />
    <Book Series="Superman/Batman" Number="3" Year="2016" />
    <Book Series="Superman/Batman" Number="4" Year="2016" />
    <Book Series="Superman/Batman" Number="5" Year="2017" />
    <Book Series="Superman/Batman" Number="6" Year="2017" />
  </Books>
</ReadingList>